spring.application.name=backend
# Sửa postgresql:// thành jdbc:postgresql://
spring.datasource.url=jdbc:postgresql://neondb_owner:npg_X7vBFCN9MQUq@ep-sweet-shape-azu1q2gu.c-3.ap-southeast-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require"
spring.datasource.username=neondb_owner
spring.datasource.password=MẬT_KHẨU_ĐÃ_HIỆN_Ở_BƯỚC_1
spring.datasource.driver-class-name=org.postgresql.Driver

# Cấu hình Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect