// Dữ liệu giả lập cho tới khi backend có API /api/jobs thật (module crawl bài đăng).
// Cấu trúc field được đặt tên giống hệt những gì backend nên trả về,
// để sau này chỉ cần đổi jobApi.js sang gọi API thật mà không cần sửa UI.
export const MOCK_JOBS = [
    {
      id: 1,
      title: "Senior Frontend Developer (React, TypeScript)",
      company: "TechNova Solutions",
      logo: "📄",
      location: "Hồ Chí Minh",
      type: "Full-time",
      experience: "3+ năm",
      salary: "2,000 - 3,500 USD",
      category: "IT / Phần mềm",
      postedAt: "2026-09-05",
      source: "topcv.vn",
    },
    {
      id: 2,
      title: "Digital Marketing Manager",
      company: "Creative Spark Agency",
      logo: "🖼️",
      location: "Hà Nội",
      type: "Full-time",
      experience: "5+ năm",
      salary: "Thỏa thuận",
      category: "Marketing",
      postedAt: "2026-09-04",
      source: "vietnamworks.com",
    },
    {
      id: 3,
      title: "Chuyên viên Phân tích Dữ liệu (Data Analyst)",
      company: "FinTech Global",
      logo: "📊",
      location: "Đà Nẵng",
      type: "Remote",
      experience: "1-3 năm",
      salary: "1,000 - 1,800 USD",
      category: "IT / Phần mềm",
      postedAt: "2026-09-03",
      source: "itviec.com",
    },
    {
      id: 4,
      title: "Nhân viên Kinh doanh B2B",
      company: "Global Trade JSC",
      logo: "💼",
      location: "Hồ Chí Minh",
      type: "Full-time",
      experience: "1-3 năm",
      salary: "8 - 15 triệu + hoa hồng",
      category: "Sales",
      postedAt: "2026-09-02",
      source: "topcv.vn",
    },
    {
      id: 5,
      title: "UI/UX Designer",
      company: "Creative Spark Agency",
      logo: "🎨",
      location: "Remote",
      type: "Part-time",
      experience: "2+ năm",
      salary: "800 - 1,200 USD",
      category: "Thiết kế",
      postedAt: "2026-09-01",
      source: "vietnamworks.com",
    },
    {
      id: 6,
      title: "Backend Developer (Java Spring Boot)",
      company: "TechNova Solutions",
      logo: "🖥️",
      location: "Hồ Chí Minh",
      type: "Full-time",
      experience: "2-4 năm",
      salary: "18 - 28 triệu",
      category: "IT / Phần mềm",
      postedAt: "2026-08-30",
      source: "itviec.com",
    },
  ];
  
  export const JOB_CATEGORIES = [
    { icon: "💻", name: "IT / Phần mềm", jobs: "1,200+ việc làm" },
    { icon: "📣", name: "Marketing", jobs: "850+ việc làm" },
    { icon: "💼", name: "Sales", jobs: "920+ việc làm" },
    { icon: "🎨", name: "Thiết kế", jobs: "450+ việc làm" },
  ];